[package]
name = "slam"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
json = "0.12.4"
plotters = { version = "0.3.7" }
icp_2d = {git = "https://github.com/johannes-adr/icp_2d.git"}
nalgebra = "0.33.2"
gs-rs = {git = "https://github.com/GameDungeon/gs-rs"}

